### ISSUE TITLE
exception in deferred followed by failure to transmit clock updates to TCP/IP clients

### ISSUE THREAD

**Issue by rstms** [rstms/txTrader#2]
Exception in deferred 

Log entry:

```
2015-11-17 11:50:50.754615500 2015-11-17 11:50:50-0600 [-] 127.0.0.1 - - [17/Nov/2015:17:50:50 +0000] "POS
T /RPC2 HTTP/1.1" 200 15460 "-" "xmlrpclib.py/1.0.1 (by www.pythonware.com)"
2015-11-17 11:50:50.755011500 2015-11-17 11:50:50-0600 [-] Unhandled error in Deferred:
2015-11-17 11:50:50.755892500 2015-11-17 11:50:50-0600 [-] Unhandled Error
2015-11-17 11:50:50.755893500   Traceback (most recent call last):
2015-11-17 11:50:50.755893500     File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1192, in run
2015-11-17 11:50:50.755894500       self.mainLoop()
2015-11-17 11:50:50.755894500     File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
2015-11-17 11:50:50.755895500       self.runUntilCurrent()
2015-11-17 11:50:50.755895500     File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
2015-11-17 11:50:50.755900500       call.func(*call.args, **call.kw)
2015-11-17 11:50:50.755901500     File "/usr/lib/python2.7/dist-packages/twisted/internet/task.py", line 218, in __call__
2015-11-17 11:50:50.755901500       d = defer.maybeDeferred(self.f, *self.a, **self.kw)
2015-11-17 11:50:50.755901500   --- <exception caught here> ---
2015-11-17 11:50:50.755902500     File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 139, in maybeDeferred
2015-11-17 11:50:50.755904500       result = f(*args, **kw)
2015-11-17 11:50:50.755904500     File "/usr/local/lib/python2.7/dist-packages/txtrader/tws.py", line 342, in EverySecond
2015-11-17 11:50:50.755905500       self.CheckPendingResults()
2015-11-17 11:50:50.755905500     File "/usr/local/lib/python2.7/dist-packages/txtrader/tws.py", line 240, in CheckPendingResults
2015-11-17 11:50:50.755905500       cblist.remove(cb)
2015-11-17 11:50:50.755907500   exceptions.ValueError: list.remove(x): x not in list
2015-11-17 11:50:50.755910500
2015-11-17 11:50:50.794655500 2015-11-17 11:50:50-0600 [-] error: <error id=-1, errorCode=2100, errorMsg=API client has been unsubscribed from account data.>
2015-11-17 11:51:53.241222500 2015-11-17 11:51:53-0600 [HTTPChannel,0,127.0.0.1] xmlrpc_status()
```

**Comment by rstms** [comment]
Re-entrancy not guaranteed by LoopingCall unless the called function returns a deferred, then the library will not reschedule untll the deferred has fired.

The function passed to LoopingCall should create a deferred, then pass the deferred using CallLater with 0 delay to the the work function.  LoopingCall's function returns the deferred immediately, and the framework won't call it again until the work function calls callback() on the deferred.

**Comment by rstms** [comment]
solved with https://github.com/rstms/txTrader/commit/5b8539544c2b6d5bb73708ca00b99440638181b4
